Repository PyDrocsid/MorpheusHelper, pull requests merged in 2020-10, with the labels that each got.

#89 Intents
  .deepsource.toml
  Pipfile
  Pipfile.lock
  docker-compose.yml
  morpheushelper.py
  util.py
Labels: bug

#90 Disconnect on mute
  cogs/mod.py
Labels: enhancement

#94 Added issue and pull request templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: enhancement

#92 Fixes
  cogs/mod.py
  cogs/polls.py
  cogs/reaction_pin.py
  cogs/voice_channel.py
  morpheushelper.py
  translations/en.yml
Labels: enhancement, hacktoberfest-accepted

#95 Alembic
  Pipfile
  Pipfile.lock
  alembic.ini
  alembic/README
  alembic/env.py
  alembic/script.py.mako
  alembic/versions/34ad7374653a_added_upgrade_columns_in_mute_and_ban.py
Labels: enhancement

#76 Experimental
  .dockerignore
  .github/workflows/docker.yml
  Pipfile
  Pipfile.lock
  README.md
  alembic.ini
  alembic/README
  alembic/env.py
  alembic/script.py.mako
  alembic/versions/34ad7374653a_added_upgrade_columns_in_mute_and_ban.py
  async_thread.py
  cogs/__init__.py
  cogs/automod.py
  cogs/betheprofessional.py
  cogs/cleverbot.py
  cogs/codeblocks.py
  cogs/discordpy_documentation.py
  cogs/info.py
  cogs/invites.py
  cogs/logging.py
  cogs/mediaonly.py
  cogs/metaquestion.py
  cogs/mod.py
  cogs/news.py
  cogs/permissions.py
  cogs/polls.py
  cogs/random_stuff_enc.py
  cogs/reaction_pin.py
  cogs/reactionrole.py
  cogs/reddit.py
  cogs/rules.py
  cogs/verification.py
  cogs/voice_channel.py
  database.py
  info.py
  models/allowed_invite.py
  models/btp_role.py
  models/cleverbot_channel.py
  models/dynamic_voice.py
  models/log_exclude.py
  models/mediaonly_channel.py
  models/mod.py
  models/news_authorization.py
  models/permissions.py
  models/reactionpin_channel.py
  models/reactionrole.py
  models/reddit.py
  models/role_voice_link.py
  models/settings.py
  models/verification_role.py
  morpheushelper.py
  multilock.py
  permission.py
  permissions.py
  translations.py
  translations/en.yml
  util.py
Labels: hacktoberfest-accepted

#96 Docker
  .github/workflows/docker.yml
  Dockerfile
  Pipfile
  Pipfile.lock
  morpheushelper/cleverbot_api.py
  morpheushelper/cogs/__init__.py
  morpheushelper/cogs/automod.py
  morpheushelper/cogs/betheprofessional.py
  morpheushelper/cogs/cleverbot.py
  morpheushelper/cogs/codeblocks.py
  morpheushelper/cogs/discordpy_documentation.py
  morpheushelper/cogs/info.py
  morpheushelper/cogs/invites.py
  morpheushelper/cogs/logging.py
  morpheushelper/cogs/mediaonly.py
  morpheushelper/cogs/metaquestion.py
  morpheushelper/cogs/mod.py
  morpheushelper/cogs/news.py
  morpheushelper/cogs/permissions.py
  morpheushelper/cogs/polls.py
  morpheushelper/cogs/reaction_pin.py
  morpheushelper/cogs/reactionrole.py
  morpheushelper/cogs/reddit.py
  morpheushelper/cogs/rules.py
  morpheushelper/cogs/verification.py
  morpheushelper/cogs/voice_channel.py
  morpheushelper/info.py
  morpheushelper/models/allowed_invite.py
  morpheushelper/models/btp_role.py
  morpheushelper/models/cleverbot_channel.py
  morpheushelper/models/dynamic_voice.py
  morpheushelper/models/log_exclude.py
  morpheushelper/models/mediaonly_channel.py
  morpheushelper/models/mod.py
  morpheushelper/models/news_authorization.py
  morpheushelper/models/reactionpin_channel.py
  morpheushelper/models/reactionrole.py
  morpheushelper/models/reddit.py
  morpheushelper/models/role_voice_link.py
  morpheushelper/models/verification_role.py
  morpheushelper/morpheushelper.py
  morpheushelper/permissions.py
  morpheushelper/util.py
Labels: enhancement

#97 added teampoll command
  morpheushelper/cogs/polls.py
  translations/en.yml
Labels: enhancement

#99 added guild name to update function for allowed_invites
  morpheushelper/cogs/invites.py
  morpheushelper/models/allowed_invite.py
Labels: enhancement

#98 Added wastebasket feature for polls
  morpheushelper/cogs/metaquestion.py
  morpheushelper/cogs/polls.py
  morpheushelper/permissions.py
  morpheushelper/util.py
  translations/en.yml
Labels: enhancement
