Repository PyDrocsid/MorpheusHelper, pull requests merged in 2021-03, with the labels that each got.

#153 Added cancel function for message sending/editing
  morpheushelper/cogs/rules.py
  translations/en.yml
Labels: enhancement

#151 Added channel hopping warn
  morpheushelper/cogs/__init__.py
  morpheushelper/cogs/alert_channel.py
  morpheushelper/cogs/rules.py
  morpheushelper/colours.py
  translations/en.yml
Labels: enhancement

#162 Workaround for reddit title link exploit
  morpheushelper/cogs/reddit.py
Labels: bug

#165 Added parsing for html special characters in reddit post titles
  morpheushelper/cogs/reddit.py
Labels: bug

#156 User joined cog added
  morpheushelper/cogs/__init__.py
  morpheushelper/cogs/joined_info.py
  translations/en.yml
Labels: enhancement

#150 Removed print and added logger
  morpheushelper/cogs/invites.py
  morpheushelper/cogs/reddit.py
  morpheushelper/cogs/voice_channel.py
  morpheushelper/emkc_api.py
  morpheushelper/morpheushelper.py
Labels: enhancement

#166 v2.3.0
  Dockerfile
  README.md
  morpheushelper/cogs/__init__.py
  morpheushelper/cogs/alert_channel.py
  morpheushelper/cogs/invites.py
  morpheushelper/cogs/joined_info.py
  morpheushelper/cogs/reddit.py
  morpheushelper/cogs/rules.py
  morpheushelper/cogs/voice_channel.py
  morpheushelper/colours.py
  morpheushelper/emkc_api.py
  morpheushelper/morpheushelper.py
  translations/en.yml
Labels: bug, documentation, enhancement
